/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all resources
         * @description Returns resources using backend-driven filtering, sorting, and pagination.
         *
         *     Supported query params:
         *     - `page` (default `1`)
         *     - `pageSize` (default `10`, max `100`)
         *     - `status` (`draft` or `completed`)
         *     - `name` (case-insensitive partial name match)
         *     - `sortOrder` (`desc` newest first, `asc` oldest first)
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    status?: "draft" | "completed";
                    name?: string;
                    sortOrder?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resources loaded successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceListResponse"];
                    };
                };
                /** @description Invalid query parameter value */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new resource
         * @description Creates a new resource in `draft` status.
         *
         *     Business defaults on create:
         *     - `status = draft`
         *     - `resourceId` is auto-incremented
         *     - `basicInfo` and `projectDetails` are initialized with empty defaults
         *     - `resourceName` becomes immutable after creation
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateResourceInput"];
                };
            };
            responses: {
                /** @description Resource created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
                /** @description Validation error (for example missing resourceName) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a resource by id
         * @description Loads one resource using either:
         *     - numeric resourceId (for example `1`), or
         *     - Mongo ObjectId.
         *
         *     Returns 400 for invalid id format and 404 when the resource does not exist.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resource loaded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
                /** @description Invalid id format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Replace full resource data while preserving current status
         * @description Replaces resource business fields in one request:
         *     - `name`
         *     - `basicInfo`
         *     - `projectDetails`
         *
         *     Business rule:
         *     - allowed only when resource status is `completed`.
         *     - drafts cannot be replaced using this endpoint.
         *     - `name` and `basicInfo.resourceName` are immutable after create.
         *     - status is preserved and cannot be changed by this endpoint.
         *     - status transitions are handled only by `PATCH /api/resources/{id}/provisioning`.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            responses: {
                /** @description Resource replaced successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
                /** @description Invalid id format or draft resources cannot be replaced with PUT */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a resource
         * @description Permanently deletes a resource by numeric resourceId or Mongo ObjectId.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resource deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
                /** @description Invalid id format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{id}/basic-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update basic info module (draft resources only)
         * @description Updates the Basic Info module only when resource status is `draft`.
         *
         *     Business rule:
         *     - `resourceName` is immutable and cannot be changed after create.
         *     - Completed resources cannot be updated via module PATCH endpoints.
         *     - To edit completed resources, update in frontend memory and persist with `PUT /api/resources/{id}`.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BasicInfo"];
                };
            };
            responses: {
                /** @description Basic Info updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
                /** @description Invalid id format or completed-resource module PATCH is not allowed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/resources/{id}/project-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update project details module (draft resources only)
         * @description Updates the Project Details module only when resource status is `draft`.
         *
         *     Business rule:
         *     - Basic Info must be completed first.
         *     - Completed resources cannot be updated via module PATCH endpoints.
         *     - To edit completed resources, update in frontend memory and persist with `PUT /api/resources/{id}`.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            responses: {
                /** @description Project Details updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
                /** @description Invalid id format, Basic Info not completed, or completed-resource module PATCH is not allowed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/resources/{id}/provisioning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark resource as completed
         * @description The only endpoint that can change status.
         *
         *     Business rule:
         *     - Allowed only when current status is `draft`.
         *     - Basic Info and Project Details must both be complete before provisioning.
         *     - `draft -> completed` is allowed.
         *     - completed resources cannot be reprovisioned.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Provisioning result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
                /** @description Invalid id format, completed resource reprovisioning, or incomplete modules */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear all application data
         * @description Development/administration endpoint that deletes all resources from the database.
         *
         *     Use for local reset scenarios only.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Database cleared successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ResourceStatus: "draft" | "completed";
        BasicInfo: {
            resourceName?: string;
            owner?: string;
            email?: string;
            description?: string;
            /** @enum {string} */
            priority?: "low" | "medium" | "high";
        };
        ProjectDetails: {
            projectName?: string;
            budget?: string;
            category?: string;
            options?: string[];
        };
        Resource: {
            _id?: string;
            resourceId?: number;
            name?: string;
            status?: components["schemas"]["ResourceStatus"];
            basicInfo?: components["schemas"]["BasicInfo"];
            projectDetails?: components["schemas"]["ProjectDetails"];
            createdAt?: string;
            updatedAt?: string;
        };
        ResourceListResponse: {
            items?: components["schemas"]["Resource"][];
            pagination?: {
                /** @example 1 */
                page?: number;
                /** @example 10 */
                pageSize?: number;
                /** @example 24 */
                totalItems?: number;
                /** @example 3 */
                totalPages?: number;
            };
        };
        CreateResourceInput: {
            /** @example Example resource */
            resourceName: string;
        };
        ErrorResponse: {
            /** @example Resource not found */
            message?: string;
            details?: unknown;
        };
        ProvisioningResponse: components["schemas"]["Resource"] | {
            /** @example Resource is already completed */
            message?: string;
            resource?: components["schemas"]["Resource"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
